#!/usr/bin/env python3
# tools/nki_emitter/air_to_nki.py
#
# Converts MLIR (AIR dialect or pre-lowered func/scf/memref/arith) to NKI Python.
#
# Usage:
#   # From AIR dialect (runs lowering pipeline through air-opt first):
#   PYTHONPATH=my_install/python python3 tools/nki_emitter/air_to_nki.py input.mlir
#
#   # From already-lowered MLIR (e.g. test.lit #Start section):
#   PYTHONPATH=my_install/python python3 tools/nki_emitter/air_to_nki.py input.mlir --no-lower

import argparse
import os
import shutil
import subprocess
import sys

import air.ir as ir

# ---------------------------------------------------------------------------
# Lowering via air-opt subprocess
# ---------------------------------------------------------------------------

LOWER_FLAGS = ["--air-to-std", "--lower-affine", "--canonicalize", "--cse"]


def _find_air_opt(hint: str | None) -> str:
    if hint:
        return hint
    here = os.path.dirname(os.path.abspath(__file__))
    candidate = os.path.normpath(
        os.path.join(here, "..", "..", "build", "bin", "air-opt")
    )
    if os.path.isfile(candidate):
        return candidate
    found = shutil.which("air-opt")
    if found:
        return found
    raise FileNotFoundError(
        "Cannot find air-opt. Use --air-opt <path> to specify it."
    )


def lower_mlir(src: str, air_opt: str) -> str:
    """Run the AIR lowering pipeline via air-opt; return the lowered MLIR text."""
    result = subprocess.run(
        [air_opt] + LOWER_FLAGS + ["-"],
        input=src, capture_output=True, text=True,
    )
    if result.returncode != 0:
        print("air-opt failed:\n", result.stderr, file=sys.stderr)
        sys.exit(1)
    return result.stdout


# ---------------------------------------------------------------------------
# MLIR type helpers
# ---------------------------------------------------------------------------

def _type_to_nki(t: ir.Type) -> str:
    mapping = {
        "f32": "nl.float32", "f16": "nl.float16", "bf16": "nl.bfloat16",
        "i32": "nl.int32",   "i16": "nl.int16",   "i8":   "nl.int8",
        "i1":  "nl.bool_",
    }
    return mapping.get(str(t), str(t))


def _is_memref(t: ir.Type) -> bool:
    try:
        ir.MemRefType(t)
        return True
    except Exception:
        return False


def _attr_get(op: ir.Operation, key: str):
    """Safe attribute access — OpAttributeMap has no .get()."""
    return op.attributes[key] if key in op.attributes else None


def _extract_mlir_from_lit(src: str) -> str:
    """Extract the MLIR snippet from a lit-style file.

    The test file may contain a "#Start:" marker followed by a MLIR module.
    This function returns the lines between "#Start:" and the next line
    beginning with "#" (e.g. "#expected"), or the full input if no marker
    is found.
    """
    lines = src.splitlines()
    start = None
    for i, line in enumerate(lines):
        if line.strip() == "#Start:":
            start = i + 1
            break
    if start is None:
        return src

    end = None
    for j in range(start, len(lines)):
        if lines[j].lstrip().startswith("#"):
            end = j
            break
    if end is None:
        end = len(lines)

    mlir_lines = lines[start:end]
    # Trim leading/trailing blank lines.
    while mlir_lines and mlir_lines[0].strip() == "":
        mlir_lines.pop(0)
    while mlir_lines and mlir_lines[-1].strip() == "":
        mlir_lines.pop()
    return "\n".join(mlir_lines) + "\n"


# ---------------------------------------------------------------------------
# Visitor-pattern NKI emitter
# ---------------------------------------------------------------------------

class NKIEmitter:
    """
    Walks a lowered MLIR module (func/scf/memref/arith) and emits NKI Python.

    Dispatch: for op whose name is "dialect.opname", calls
    visit_dialect_opname(op), falling back to visit_default(op).

    SSA values are tracked in _vmap (id(Value) → Python name/literal).
    Fresh names for loop IVs and op results are generated by _fresh().
    Input args are named arg0/arg1/…; the last memref arg is bound to "output".
    """

    _NUMPY_OPS = {
        "arith.addf": "np.add",      "arith.addi": "np.add",
        "arith.subf": "np.subtract", "arith.subi": "np.subtract",
        "arith.mulf": "np.multiply", "arith.muli": "np.multiply",
        "arith.divf": "np.divide",
    }

    def __init__(self):
        self._lines: list[str] = []
        self._indent = 0
        self._vmap: dict[ir.Value, str] = {}   # ir.Value → Python name or literal
        self._counter = 0
        self._first_input = "arg0"        # for arg.shape[dim] in loop bounds
        self._loop_depth = 0              # incremented per non-trivial scf.for
        self._tile: tuple[int, int] | None = None

    # -----------------------------------------------------------------------
    # Visitor dispatch
    # -----------------------------------------------------------------------

    def visit(self, op: ir.Operation):
        method = "visit_" + op.operation.name.replace(".", "_")
        getattr(self, method, self.visit_default)(op)

    def visit_default(self, op: ir.Operation):
        self._emit(f"# [unhandled: {op.operation.name}]")

    # -----------------------------------------------------------------------
    # Output helpers
    # -----------------------------------------------------------------------

    def _emit(self, line: str):
        self._lines.append("    " * self._indent + line)

    def _blank(self):
        self._lines.append("")

    def _push(self): self._indent += 1
    def _pop(self):  self._indent -= 1

    def _fresh(self, hint: str = "v") -> str:
        """Allocate the next unique Python name with the given hint prefix."""
        self._counter += 1
        return f"{hint}_{self._counter}"

    def _bind(self, val: ir.Value, name: str):
        """Register a Python name for an SSA value in the symbol table."""
        # MLIR python bindings return wrapper objects that are hashable and
        # comparable, but their `id()` values are not stable across repeated
        # lookups. Use the value object itself as the key.
        self._vmap[val] = name

    def _name(self, val: ir.Value) -> str:
        """Look up the Python name for a value; auto-allocate a fresh one if missing."""
        if val not in self._vmap:
            self._vmap[val] = self._fresh()
        return self._vmap[val]

    # -----------------------------------------------------------------------
    # Module entry-point
    # -----------------------------------------------------------------------

    def emit_module(self, module: ir.Module) -> str:
        self._emit("# NKI vector addition kernel")
        self._blank()
        self._emit("import numpy as np")
        self._emit("import neuronxcc.nki as nki")
        self._emit("import neuronxcc.nki.language as nl")
        self._emit("import neuronxcc.nki.isa as nisa")
        self._blank()
        for op in module.body.operations:
            self.visit(op)
        return "\n".join(self._lines)

    # -----------------------------------------------------------------------
    # Visitors
    # -----------------------------------------------------------------------

    def visit_func_func(self, op: ir.Operation):
        func_name = ir.StringAttr(op.attributes["sym_name"]).value
        entry: ir.Block = op.regions[0].blocks[0]
        args = list(entry.arguments)

        # Partition: the last memref arg is the output (written by MLIR stores).
        # All other memref args are inputs.  We rebind the output arg to the
        # Python name "output" so nl.store automatically targets it.
        memrefs = [a for a in args if _is_memref(a.type)]
        output_arg = memrefs[-1] if memrefs else None

        input_names: list[str] = []
        idx = 0
        for arg in args:
            if arg is output_arg:
                self._bind(arg, "output")
            elif _is_memref(arg.type):
                name = f"arg{idx}"
                idx += 1
                self._bind(arg, name)
                input_names.append(name)
            # Non-memref args (index, etc.) left for _name() to handle on demand.

        self._first_input = input_names[0] if input_names else "arg0"
        self._loop_depth = 0

        self._emit("@nki.jit")
        self._emit(f"def {func_name}({', '.join(input_names)}):")
        self._push()

        # Allocate the output buffer from the first input's shape and dtype.
        if output_arg is not None:
            src = self._first_input
            self._emit(
                f"output = nl.ndarray({src}.shape, dtype={src}.dtype,"
                f" buffer=nl.shared_hbm)"
            )

        # If a tile spec was provided (set by caller), emit a tiled SPMD-style kernel.
        if self._tile is not None:
            tx, ty = self._tile

            self._emit(f"c_output = nl.ndarray({self._first_input}.shape, dtype={self._first_input}.dtype, buffer=nl.shared_hbm)")
            self._blank()

            self._emit(f"offset_i_x = nl.program_id(0) * {tx}")
            self._emit(f"offset_i_y = nl.program_id(1) * {ty}")
            self._blank()

            self._emit(f"ix = offset_i_x + nl.arange({tx})[:, None]")
            self._emit(f"iy = offset_i_y + nl.arange({ty})[None, :]")
            self._blank()

            a_name = input_names[0] if len(input_names) > 0 else self._first_input
            b_name = input_names[1] if len(input_names) > 1 else (self._first_input)
            self._emit(f"a_tile = nl.load({a_name}[ix, iy])")
            self._emit(f"b_tile = nl.load({b_name}[ix, iy])")
            self._blank()

            self._emit("c_tile = a_tile + b_tile")
            self._blank()

            self._emit("nl.store(c_output[ix, iy], value=c_tile)")
            self._blank()

            self._emit("return c_output")
            self._pop()
            self._blank()
            return

        for inner in entry.operations:
            self.visit(inner)
        self._pop()
        self._blank()

    def visit_func_return(self, op: ir.Operation):
        self._emit("return output")

    # --- arith constants are inlined as literals; no Python statement emitted ---

    def visit_arith_constant(self, op: ir.Operation):
        attr = _attr_get(op, "value")
        try:
            literal = str(ir.IntegerAttr(attr).value)
        except Exception:
            try:
                literal = repr(ir.FloatAttr(attr).value)
            except Exception:
                literal = str(attr)
        # Bind the result value to the literal string.
        # Any use of this value via _name() will inline the literal directly.
        self._bind(op.results[0], literal)

    # --- index casts are transparent: alias the result to the operand ---

    def visit_arith_index_cast(self, op: ir.Operation):
        self._bind(op.results[0], self._name(op.operands[0]))

    visit_arith_index_castui = visit_arith_index_cast

    # --- scf.for: fold trivial 1-trip loops, otherwise emit nl.affine_range ---

    def visit_scf_for(self, op: ir.Operation):
        lb   = self._name(op.operands[0])
        ub   = self._name(op.operands[1])
        step = self._name(op.operands[2])

        body: ir.Block = op.regions[0].blocks[0]
        iv = body.arguments[0]

        # Fold trivial single-trip loops (from air.launch 1x1 grids).
        # These have lb=0, ub=1, step=1 and only exist as lowering artifacts.
        try:
            if int(lb) == 0 and int(ub) == 1 and int(step) == 1:
                self._bind(iv, "0")
                for inner in body.operations:
                    self.visit(inner)
                return
        except ValueError:
            pass  # runtime bounds — cannot fold statically

        iv_name = self._fresh("i")
        self._bind(iv, iv_name)

        # Use arg.shape[dim] for the upper bound so the kernel is shape-agnostic
        # rather than baking in the literal constant from the IR.
        shape_ub = f"{self._first_input}.shape[{self._loop_depth}]"
        try:
            # Standard case: lb=0, step=1 → single-argument nl.affine_range(ub)
            if int(lb) == 0 and int(step) == 1:
                self._emit(f"for {iv_name} in nl.affine_range({shape_ub}):")
            else:
                self._emit(
                    f"for {iv_name} in nl.affine_range({lb}, {shape_ub}, {step}):"
                )
        except ValueError:
            # Runtime lb/step: keep them verbatim, still substitute shape-based ub.
            self._emit(
                f"for {iv_name} in nl.affine_range({lb}, {shape_ub}, {step}):"
            )

        self._push()
        self._loop_depth += 1
        for inner in body.operations:
            self.visit(inner)
        self._loop_depth -= 1
        self._pop()

    def visit_scf_yield(self, op: ir.Operation):
        pass  # Plain yields with no loop-carried values need no Python statement.

    # --- memref loads/stores ---

    def visit_memref_load(self, op: ir.Operation):
        mem = self._name(op.operands[0])
        idx = ", ".join(self._name(op.operands[i]) for i in range(1, len(op.operands)))
        res = self._fresh("val")
        self._bind(op.results[0], res)
        self._emit(f"{res} = nl.load({mem}[{idx}])")

    def visit_memref_store(self, op: ir.Operation):
        val = self._name(op.operands[0])
        mem = self._name(op.operands[1])
        idx = ", ".join(self._name(op.operands[i]) for i in range(2, len(op.operands)))
        self._emit(f"nl.store({mem}[{idx}], value={val})")

    # --- arith binary ops → nisa.tensor_tensor ---

    def _visit_arith_binop(self, op: ir.Operation):
        np_op = self._NUMPY_OPS[op.operation.name]
        lhs = self._name(op.operands[0])
        rhs = self._name(op.operands[1])
        res = self._fresh("res")
        self._bind(op.results[0], res)
        self._emit(f"{res} = nisa.tensor_tensor({lhs}, {rhs}, op={np_op})")

    # Wire every supported binary op to the shared helper via the visitor protocol.
    visit_arith_addf = _visit_arith_binop
    visit_arith_subf = _visit_arith_binop
    visit_arith_mulf = _visit_arith_binop
    visit_arith_divf = _visit_arith_binop
    visit_arith_addi = _visit_arith_binop
    visit_arith_subi = _visit_arith_binop
    visit_arith_muli = _visit_arith_binop


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Convert MLIR (AIR dialect or lowered) to NKI Python.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("input", help="Input .mlir file")
    parser.add_argument("-o", "--output", default=None,
                        help="Output .py file (default: stdout)")
    parser.add_argument("--air-opt", dest="air_opt", default=None,
                        help="Path to air-opt binary (auto-detected if not set)")
    parser.add_argument(
        "--no-lower", action="store_true",
        help="Skip air-opt lowering: input is already in func/scf/memref/arith "
             "(use this for the #Start section of test.lit)",
    )
    parser.add_argument(
        "--tile", dest="tile", default=None,
        help="Optional tile sizes as WIDTHxHEIGHT (e.g. 128x512) to emit a tiled kernel",
    )
    args = parser.parse_args()

    with open(args.input) as f:
        src = f.read()

    # If the input is a lit-style test file, only keep the MLIR in the #Start section.
    src = _extract_mlir_from_lit(src)

    if not args.no_lower:
        air_opt = _find_air_opt(args.air_opt)
        src = lower_mlir(src, air_opt)

    # Parse tile option into a tuple if provided
    tile: tuple[int, int] | None = None
    if args.tile:
        try:
            parts = args.tile.split("x")
            tile = (int(parts[0]), int(parts[1]))
        except Exception:
            print("Invalid --tile format. Use WIDTHxHEIGHT, e.g. 128x512", file=sys.stderr)
            sys.exit(1)

    with ir.Context() as ctx:
        ctx.allow_unregistered_dialects = True
        module = ir.Module.parse(src)
        emitter = NKIEmitter()
        # Set tile on emitter if provided (keeps backward compatibility)
        if tile is not None:
            emitter._tile = tile
        nki_src = emitter.emit_module(module)

    if args.output:
        with open(args.output, "w") as f:
            f.write(nki_src)
        print(f"Wrote NKI Python to: {args.output}", file=sys.stderr)
    else:
        print(nki_src)


if __name__ == "__main__":
    main()
